[workspace]
members = [
    "crates/hns-primitives",
    "crates/hns-consensus",
    "crates/hns-goosig",
    "crates/hns-secp256k1",
    "crates/hns-chain",
    "crates/hns-state",
    "crates/hns-store",
    "crates/hns-p2p",
    "crates/hns-sync",
    "crates/hns-mempool",
    "crates/hns-mining",
    "crates/hns-rpc",
    "crates/hns-node",
    "crates/hns-testkit",
    "crates/hns-urkel",
    "crates/hns-resolver",
    "crates/hns-wallet-index",
    "crates/hns-denuo-market-relay",
]
exclude = ["fuzz"]
resolver = "2"

[workspace.package]
version = "0.3.5"
edition = "2021"
license = "ISC"
publish = false
repository = "https://github.com/handshake-rs/hns-node-rs"

[workspace.dependencies]
ahash = "0.8"
anyhow = "1.0"
chacha20poly1305 = "0.10"
clap = { version = "4.5", features = ["derive", "env"] }
hns-covenants = { version = "=0.2.0", git = "https://github.com/handshake-rs/hns-rs.git", rev = "4331eee2265ebc43a28390517c24a958fa4b7733" }
hns-dns-relay-protocol = { version = "=0.2.0", git = "https://github.com/handshake-rs/hns-rs.git", rev = "4331eee2265ebc43a28390517c24a958fa4b7733" }
hns-hnsr-protocol = { version = "=0.2.0", git = "https://github.com/handshake-rs/hns-rs.git", rev = "4331eee2265ebc43a28390517c24a958fa4b7733" }
hns-odoh-protocol = { version = "=0.2.0", git = "https://github.com/handshake-rs/hns-rs.git", rev = "4331eee2265ebc43a28390517c24a958fa4b7733" }
hns-p2p-experimental = { version = "=0.2.0", git = "https://github.com/handshake-rs/hns-rs.git", rev = "4331eee2265ebc43a28390517c24a958fa4b7733" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.9"
thiserror = "2.0"
tokio = { version = "1.38", features = ["io-util", "macros", "net", "rt-multi-thread", "signal", "sync", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
