[package]
name = "hns-store"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
fs4 = { version = "=1.1.0", default-features = false, features = ["sync"] }
hns-primitives = { path = "../hns-primitives" }
hns-urkel = { path = "../hns-urkel" }
redb = "=4.2.0"
serde.workspace = true
thiserror.workspace = true
