[package]
name = "hns-consensus"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
hns-primitives = { path = "../hns-primitives" }
hns-secp256k1 = { path = "../hns-secp256k1" }
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
