[package]
name = "meshmine-minerd"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
hex = "0.4"
libc = "0.2"
meshmine-gateway = { path = "../../../crates/meshmine-gateway" }
meshmine-hns = { path = "../../../crates/meshmine-hns" }
meshmine-storage = { path = "../../../crates/meshmine-storage" }
meshmine-types = { path = "../../../crates/meshmine-types" }
meshmine-work = { path = "../../../crates/meshmine-work" }
hns-consensus = { path = "../hns-consensus" }
hns-mempool = { path = "../hns-mempool" }
hns-mining = { path = "../hns-mining" }
hns-node = { path = "../hns-node" }
hns-primitives = { path = "../hns-primitives" }
hns-store = { path = "../hns-store" }
tokio.workspace = true
tracing.workspace = true
