[package]
name = "hns-sync"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
hns-primitives = { path = "../hns-primitives" }
hns-chain = { path = "../hns-chain" }
hns-p2p = { path = "../hns-p2p" }
hns-store = { path = "../hns-store", default-features = false }
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
